"""Generate a professional PADER-style PDF report using ReportLab Platypus.

Entry points:
    python -m src.report.pdf_generator          # uses defaults
    python -m src.report.pdf_generator --help   # full CLI

Charts are built exclusively from data/analysis_results.json (deterministic).
Text sections are taken verbatim from output/pader_report.json.
Evidence IDs are preserved in every section and in the appendix.
"""
from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from reportlab.graphics import renderPDF
from reportlab.graphics.shapes import Drawing, Line, Rect, String
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    FrameBreak,
    HRFlowable,
    Image,
    KeepTogether,
    NextPageTemplate,
    PageBreak,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.platypus.flowables import Flowable

from .charts import (
    age_group_chart,
    country_distribution_chart,
    monthly_trend_chart,
    outcome_distribution_chart,
    serious_vs_nonserious_chart,
    sex_distribution_chart,
    top_reactions_chart,
)
from .styles import (
    GOLD,
    LIGHT_GREY,
    MID_GREY,
    NAVY,
    NAVY_LIGHT,
    SLATE,
    WARN_BG,
    WARN_BORDER,
    Styles,
    standard_table_style,
)
from .tables import (
    alert_summary_table,
    case_index_table,
    case_summary_table,
    country_table,
    demographics_table,
    evidence_appendix_table,
    monthly_trend_table,
    outcome_table,
    reaction_frequency_table,
)

# ── Page geometry ────────────────────────────────────────────────────────────
PAGE_W, PAGE_H = A4
MARGIN_LEFT   = 20 * mm
MARGIN_RIGHT  = 20 * mm
MARGIN_TOP    = 28 * mm
MARGIN_BOTTOM = 22 * mm
CONTENT_W     = PAGE_W - MARGIN_LEFT - MARGIN_RIGHT

DISCLAIMER = (
    "TECHNICAL EVALUATION EXERCISE — NOT A REAL REGULATORY SUBMISSION. "
    "This document was generated by the GenAR system for demonstration and "
    "assessment purposes only. It does not constitute pharmacovigilance advice "
    "and must not be submitted to any regulatory authority."
)


# ── Drawing flowable wrapper ─────────────────────────────────────────────────

class DrawingFlowable(Flowable):
    """Wrap a ReportLab Drawing so it flows naturally in a Platypus story."""

    def __init__(self, drawing: Drawing) -> None:
        Flowable.__init__(self)
        self._drawing = drawing
        self.width  = drawing.width
        self.height = drawing.height

    def draw(self) -> None:
        renderPDF.draw(self._drawing, self.canv, 0, 0)

    def wrap(self, availW: float, availH: float) -> tuple[float, float]:
        return self.width, self.height


# ── Cover page drawing ───────────────────────────────────────────────────────

def _build_cover_drawing(
    product: str,
    period_start: str,
    period_end: str,
    generated_date: str,
    model_name: str,
) -> Drawing:
    """Return a full-page Drawing that forms the cover page."""
    w, h = PAGE_W, PAGE_H
    d = Drawing(w, h)

    # Background fill
    d.add(Rect(0, 0, w, h, fillColor=NAVY, strokeColor=None))

    # Gold accent bar top
    d.add(Rect(0, h - 8 * mm, w, 8 * mm, fillColor=GOLD, strokeColor=None))

    # Lighter panel for meta block (lower third)
    panel_h = 90 * mm
    d.add(Rect(0, 0, w, panel_h,
               fillColor=colors.HexColor("#111F42"), strokeColor=None))
    d.add(Line(0, panel_h, w, panel_h, strokeColor=GOLD, strokeWidth=1.5))

    # Gold accent bar bottom
    d.add(Rect(0, 0, w, 6 * mm, fillColor=GOLD, strokeColor=None))

    # Vertical left accent stripe
    d.add(Rect(MARGIN_LEFT - 5 * mm, panel_h, 3, h - panel_h - 8 * mm,
               fillColor=GOLD, strokeColor=None))

    # --- DISCLAIMER BAND ---
    dband_h = 14 * mm
    d.add(Rect(0, panel_h - dband_h, w, dband_h,
               fillColor=colors.HexColor("#7A1800"), strokeColor=None))
    d.add(String(
        w / 2, panel_h - dband_h + 4,
        "⚠  TECHNICAL EVALUATION EXERCISE — NOT A REAL REGULATORY SUBMISSION  ⚠",
        fontName="Helvetica-Bold",
        fontSize=8,
        fillColor=colors.HexColor("#FFD700"),
        textAnchor="middle",
    ))

    # --- Main title block ---
    tx = MARGIN_LEFT + 2 * mm
    ty = h - 38 * mm

    d.add(String(tx, ty, "PERIODIC ADVERSE DRUG EXPERIENCE REPORT",
                 fontName="Helvetica-Bold", fontSize=10,
                 fillColor=GOLD, textAnchor="start"))
    d.add(String(tx, ty - 16, "PADER-STYLE SAFETY REPORT",
                 fontName="Helvetica", fontSize=8.5,
                 fillColor=colors.HexColor("#8BAAD4"), textAnchor="start"))

    # Product name — large
    d.add(String(tx, ty - 44, product,
                 fontName="Helvetica-Bold", fontSize=36,
                 fillColor=colors.white, textAnchor="start"))

    # Divider
    d.add(Line(tx, ty - 56, w - MARGIN_RIGHT, ty - 56,
               strokeColor=GOLD, strokeWidth=0.8))

    # Report type subtitle
    d.add(String(tx, ty - 70, "Periodic Adverse Drug Experience Report (PADER-style)",
                 fontName="Helvetica", fontSize=12,
                 fillColor=colors.HexColor("#B0C4DE"), textAnchor="start"))

    # --- Meta block (lower panel) ---
    mx = MARGIN_LEFT
    my = panel_h - dband_h - 12 * mm

    meta_items = [
        ("Reporting Period",   f"{period_start}  to  {period_end}"),
        ("Application Number", "Not supplied"),
        ("Report Generated",   generated_date),
        ("Generation Engine",  model_name),
        ("Report Format",      "ICH E2C(R2)-aligned PADER-style"),
    ]
    row_h = 10 * mm
    for i, (label, value) in enumerate(meta_items):
        yy = my - i * row_h
        d.add(String(mx, yy, label + ":",
                     fontName="Helvetica-Bold", fontSize=8,
                     fillColor=GOLD, textAnchor="start"))
        d.add(String(mx + 52 * mm, yy, value,
                     fontName="Helvetica", fontSize=8,
                     fillColor=colors.HexColor("#CBD5E0"), textAnchor="start"))

    # GenAR system identification
    d.add(String(w / 2, 8 * mm + 2,
                 "Generated by GenAR v0 — Evidence-Grounded PADER Report System",
                 fontName="Helvetica", fontSize=7,
                 fillColor=NAVY, textAnchor="middle"))

    return d


# ── Header / Footer callbacks ────────────────────────────────────────────────

def _make_header_footer(product: str, report_period: str):
    def on_page(canvas, doc):
        canvas.saveState()
        page_num = doc.page

        # Skip header/footer on cover (page 1)
        if page_num == 1:
            canvas.restoreState()
            return

        # ── Header ──
        header_y = PAGE_H - MARGIN_TOP + 8 * mm
        # Left: product name
        canvas.setFont("Helvetica-Bold", 7.5)
        canvas.setFillColor(NAVY)
        canvas.drawString(MARGIN_LEFT, header_y, product.upper())
        # Centre: report type
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(SLATE)
        canvas.drawCentredString(PAGE_W / 2, header_y, "PADER-STYLE SAFETY REPORT")
        # Right: period
        canvas.drawRightString(PAGE_W - MARGIN_RIGHT, header_y, report_period)
        # Rule
        canvas.setStrokeColor(GOLD)
        canvas.setLineWidth(0.8)
        canvas.line(MARGIN_LEFT, header_y - 2.5 * mm,
                    PAGE_W - MARGIN_RIGHT, header_y - 2.5 * mm)

        # ── Footer ──
        footer_y = MARGIN_BOTTOM - 10 * mm
        # Disclaimer
        canvas.setFont("Helvetica-Oblique", 6.5)
        canvas.setFillColor(SLATE)
        canvas.drawCentredString(PAGE_W / 2, footer_y + 4 * mm,
                                 "TECHNICAL EVALUATION EXERCISE — NOT A REGULATORY SUBMISSION")
        # Rule
        canvas.setStrokeColor(MID_GREY)
        canvas.setLineWidth(0.5)
        canvas.line(MARGIN_LEFT, footer_y + 3 * mm,
                    PAGE_W - MARGIN_RIGHT, footer_y + 3 * mm)
        # Page number
        canvas.setFont("Helvetica", 7.5)
        canvas.setFillColor(SLATE)
        canvas.drawCentredString(PAGE_W / 2, footer_y,
                                 f"Page {page_num}")
        canvas.restoreState()

    return on_page


# ── Section helpers ──────────────────────────────────────────────────────────

def _section_heading(number: str, title: str) -> list:
    """Return flowables for a numbered section heading with gold underline."""
    label = f"{number}  {title}" if number else title
    return [
        Spacer(1, 4 * mm),
        Paragraph(label, Styles.h1),
        HRFlowable(width=CONTENT_W, thickness=1.2, color=GOLD, spaceAfter=4),
        Spacer(1, 2 * mm),
    ]


def _sub_heading(title: str) -> list:
    return [Spacer(1, 2 * mm), Paragraph(title, Styles.h2)]


def _ev_tag(ev_ids: list[str]) -> Paragraph:
    ids_text = "  ".join(f"[{i}]" for i in ev_ids)
    return Paragraph(
        f"<font color='#2A4380'><b>Evidence: </b>{ids_text}</font>",
        Styles.body_small,
    )


def _warn_box(text: str) -> Table:
    """An amber warning / notice box."""
    cell = Paragraph(text, Styles.body_small)
    t = Table([[cell]], colWidths=[CONTENT_W])
    t.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), WARN_BG),
        ("BOX",           (0, 0), (-1, -1), 1.0, WARN_BORDER),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
        ("TOPPADDING",    (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    return t


def _chart_block(drawing: Drawing, caption: str) -> list:
    return [
        Spacer(1, 3 * mm),
        DrawingFlowable(drawing),
        Paragraph(caption, Styles.caption),
        Spacer(1, 2 * mm),
    ]


# ── Section builders ─────────────────────────────────────────────────────────

def _build_cover(
    story: list,
    report: dict[str, Any],
    analysis: dict[str, Any],
) -> None:
    period_start = analysis["reporting_period"]["start_date"]["value"]
    period_end   = analysis["reporting_period"]["end_date"]["value"]
    generated    = report.get("generation_timestamp", "")[:10]
    model_name   = report.get("model_name", "GenAR")

    cover_d = _build_cover_drawing(
        product="Bisoprolol",
        period_start=period_start,
        period_end=period_end,
        generated_date=generated,
        model_name=model_name,
    )
    story.append(DrawingFlowable(cover_d))
    story.append(PageBreak())


def _get_section(report: dict[str, Any], name: str) -> dict[str, Any]:
    for s in report.get("sections", []):
        if s["section_name"] == name:
            return s
    return {}


def _section_text(section: dict[str, Any]) -> str:
    content = section.get("generated_content", "")
    if isinstance(content, list):
        return f"[Structured listing — {len(content)} rows. See Case Index / Listing section.]"
    return str(content)


def _build_toc(story: list, sections: list[str]) -> None:
    story += _section_heading("", "Table of Contents")
    toc_data = [
        [Paragraph("<b>Section</b>", Styles.table_cell_bold),
         Paragraph("<b>Title</b>",   Styles.table_cell_bold)]
    ]
    for i, name in enumerate(sections, 1):
        toc_data.append([
            Paragraph(str(i), Styles.table_cell_center),
            Paragraph(name,   Styles.table_cell),
        ])
    toc_data.append([
        Paragraph("App.", Styles.table_cell_center),
        Paragraph("Evidence / Traceability Appendix", Styles.table_cell),
    ])
    t = Table(toc_data, colWidths=[20 * mm, CONTENT_W - 20 * mm])
    t.setStyle(standard_table_style())
    story.append(t)
    story.append(PageBreak())


def _build_reporting_period(story: list, report: dict, analysis: dict) -> None:
    section = _get_section(report, "Reporting Period")
    story += _section_heading("1", "Reporting Period")
    story.append(Paragraph(_section_text(section), Styles.body))
    period = analysis["reporting_period"]
    data = [
        [Paragraph("<b>Attribute</b>", Styles.table_header),
         Paragraph("<b>Value</b>", Styles.table_header),
         Paragraph("<b>Source Fields</b>", Styles.table_header)],
        [Paragraph("Period Start", Styles.table_cell_bold),
         Paragraph(period["start_date"]["value"], Styles.table_cell),
         Paragraph(", ".join(period["start_date"].get("source_fields", [])), Styles.body_small)],
        [Paragraph("Period End", Styles.table_cell_bold),
         Paragraph(period["end_date"]["value"], Styles.table_cell),
         Paragraph(", ".join(period["end_date"].get("source_fields", [])), Styles.body_small)],
    ]
    t = Table(data, colWidths=[50 * mm, 45 * mm, 90 * mm])
    t.setStyle(standard_table_style())
    story.append(t)
    story.append(Spacer(1, 3 * mm))
    story.append(_ev_tag(section.get("evidence_ids", [])))
    story.append(PageBreak())


def _build_narrative(story: list, report: dict, analysis: dict) -> None:
    section = _get_section(report, "Narrative Summary and Analysis")
    story += _section_heading("2", "Narrative Summary and Analysis")
    story.append(Paragraph(_section_text(section), Styles.body))
    story.append(Spacer(1, 3 * mm))

    # Case summary stats table
    story += _sub_heading("2.1  Case Summary Statistics")
    story.append(case_summary_table(analysis["case_summary"]))
    story.append(Spacer(1, 3 * mm))

    # Chart: serious vs non-serious
    chart = serious_vs_nonserious_chart(analysis["case_summary"])
    story += _chart_block(chart, "Figure 2.1 — Case Seriousness Distribution. Source: analysis_results.json, deterministic.")

    story.append(_ev_tag(section.get("evidence_ids", [])))
    story.append(PageBreak())


def _build_case_summary(story: list, report: dict, analysis: dict) -> None:
    section = _get_section(report, "Summary Analysis of Cases")
    story += _section_heading("3", "Summary Analysis of Cases")
    story.append(Paragraph(_section_text(section), Styles.body))
    story.append(Spacer(1, 3 * mm))

    # Demographics
    story += _sub_heading("3.1  Demographic Distribution")
    age_data     = analysis["demographics"]["age_group_distribution"]["value"]
    sex_data     = analysis["demographics"]["sex_distribution"]["value"]
    country_data = analysis["demographics"]["country_distribution"]["value"]
    story.append(demographics_table(age_data, sex_data))
    story.append(Spacer(1, 3 * mm))

    # Charts side by side via a two-column Table
    age_chart = age_group_chart(age_data, width=90 * mm, height=72 * mm)
    sex_chart = sex_distribution_chart(sex_data, width=90 * mm, height=72 * mm)
    chart_row = Table(
        [[DrawingFlowable(age_chart), DrawingFlowable(sex_chart)]],
        colWidths=[93 * mm, 93 * mm],
    )
    chart_row.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP"),
                                    ("LEFTPADDING", (0,0),(-1,-1), 0),
                                    ("RIGHTPADDING",(0,0),(-1,-1), 0)]))
    story.append(chart_row)
    story.append(Paragraph(
        "Figure 3.1 — Age-group (left) and sex (right) distributions. "
        "Source: analysis_results.json, deterministic.",
        Styles.caption,
    ))
    story.append(Spacer(1, 3 * mm))

    # Country chart
    story += _sub_heading("3.2  Occurrence Country Distribution")
    story.append(country_table(country_data))
    story.append(Spacer(1, 3 * mm))
    country_chart = country_distribution_chart(country_data, width=CONTENT_W, height=90 * mm)
    story += _chart_block(country_chart, "Figure 3.2 — Top 10 occurrence countries. Source: analysis_results.json, deterministic.")

    story.append(_ev_tag(section.get("evidence_ids", [])))
    story.append(PageBreak())


def _build_reaction_analysis(story: list, report: dict, analysis: dict) -> None:
    section = _get_section(report, "Reaction / Adverse Event Analysis")
    story += _section_heading("4", "Reaction / Adverse Event Analysis")
    story.append(Paragraph(_section_text(section), Styles.body))
    story.append(Spacer(1, 3 * mm))

    reaction_data = analysis["reactions"]["reaction_counts"]["value"]
    story += _sub_heading("4.1  Top 20 Reported Preferred Terms")
    story.append(reaction_frequency_table(reaction_data, top_n=20))
    story.append(Spacer(1, 3 * mm))

    chart = top_reactions_chart(reaction_data, top_n=12, width=CONTENT_W, height=110 * mm)
    story += _chart_block(chart, "Figure 4.1 — Top 12 reported Preferred Terms (all cases). Source: analysis_results.json, deterministic.")

    story.append(_warn_box(
        "Note: These counts describe Preferred Terms supplied in the source dataset. "
        "No System Organ Class is inferred. No causal relationship is established."
    ))
    story.append(Spacer(1, 3 * mm))
    story.append(_ev_tag(section.get("evidence_ids", [])))
    story.append(PageBreak())


def _build_serious_alerts(story: list, report: dict, analysis: dict) -> None:
    section = _get_section(report, "Serious Cases / 15-Day Alerts")
    story += _section_heading("5", "Serious Cases / 15-Day Alerts")
    story.append(Paragraph(_section_text(section), Styles.body))
    story.append(Spacer(1, 3 * mm))

    alerts = analysis.get("alerts", {})
    story += _sub_heading("5.1  Alert Case Summary")
    story.append(alert_summary_table(alerts))
    story.append(Spacer(1, 3 * mm))

    # Alert reactions
    alert_reactions = alerts.get("reaction_distribution", {}).get("value", [])
    if alert_reactions:
        story += _sub_heading("5.2  Top Alert Case Preferred Terms")
        story.append(reaction_frequency_table(alert_reactions, top_n=15,
                                               title_col="Alert Case Preferred Term"))
        story.append(Spacer(1, 3 * mm))

    # Outcome chart
    outcome_data = analysis["outcomes"]["outcome_distribution"]["value"]
    story += _sub_heading("5.3  Reaction Outcome Distribution")
    story.append(outcome_table(outcome_data))
    story.append(Spacer(1, 3 * mm))
    out_chart = outcome_distribution_chart(outcome_data, width=CONTENT_W, height=80 * mm)
    story += _chart_block(out_chart, "Figure 5.1 — Reaction outcome distribution. Source: analysis_results.json, deterministic.")

    story.append(_warn_box(
        "Expectedness was not assessed because no product label or CCDS was supplied. "
        "Alert status reflects the supplied 'fulfillexpeditecriteria' field only."
    ))
    story.append(Spacer(1, 3 * mm))
    story.append(_ev_tag(section.get("evidence_ids", [])))
    story.append(PageBreak())


def _build_trends(story: list, report: dict, analysis: dict) -> None:
    section = _get_section(report, "Trends and Important Observations")
    story += _section_heading("6", "Trends and Important Observations")
    story.append(Paragraph(_section_text(section), Styles.body))
    story.append(Spacer(1, 3 * mm))

    trends = analysis.get("trends", {})
    cases_by_month   = trends.get("cases_by_month", {}).get("value", [])
    serious_by_month = trends.get("serious_cases_by_month", {}).get("value", [])

    if cases_by_month:
        story += _sub_heading("6.1  Monthly Case Counts")
        story.append(monthly_trend_table(cases_by_month, serious_by_month))
        story.append(Spacer(1, 3 * mm))
        trend_chart = monthly_trend_chart(cases_by_month, serious_by_month,
                                          width=CONTENT_W, height=90 * mm)
        story += _chart_block(trend_chart,
                               "Figure 6.1 — Monthly case trend. "
                               "Source: analysis_results.json, deterministic. "
                               "Observed patterns only — not safety-signal determinations.")

    story.append(_warn_box(
        "Observed trends are numerical descriptions only and are not safety-signal "
        "conclusions. No statistical testing has been performed."
    ))
    story.append(Spacer(1, 3 * mm))
    story.append(_ev_tag(section.get("evidence_ids", [])))
    story.append(PageBreak())


def _build_history_of_actions(story: list, report: dict) -> None:
    section = _get_section(report, "History of Actions")
    story += _section_heading("7", "History of Actions")
    story.append(Paragraph(_section_text(section), Styles.body))
    story.append(Spacer(1, 3 * mm))
    story.append(_ev_tag(section.get("evidence_ids", [])))
    story.append(PageBreak())


def _build_case_index(story: list, report: dict) -> None:
    section = _get_section(report, "Case Index / Listing")
    story += _section_heading("8", "Case Index / Listing")
    content = section.get("generated_content", [])
    total_rows = len(content) if isinstance(content, list) else 0

    story.append(Paragraph(
        f"This section provides the structured case listing with {total_rows} source rows "
        f"({len({str(r.get('case_id')) for r in content} if isinstance(content, list) else set())} unique cases). "
        "The first 50 rows are shown; the complete listing is available in the JSON report.",
        Styles.body,
    ))
    story.append(Spacer(1, 3 * mm))

    if isinstance(content, list) and content:
        story.append(case_index_table(content, max_rows=50))
        if total_rows > 50:
            story.append(Paragraph(
                f"… {total_rows - 50} additional rows not shown. "
                "See output/pader_report.json for the complete listing.",
                Styles.footnote,
            ))
    story.append(Spacer(1, 3 * mm))
    story.append(_ev_tag(section.get("evidence_ids", [])))
    story.append(PageBreak())


def _build_data_limitations(story: list, report: dict, analysis: dict) -> None:
    section = _get_section(report, "Data Limitations")
    story += _section_heading("9", "Data Limitations")
    story.append(Paragraph(_section_text(section), Styles.body))
    story.append(Spacer(1, 2 * mm))

    # Also include the limitations from analysis_results.json for completeness
    limitations = analysis.get("limitations", [])
    if limitations:
        story += _sub_heading("9.1  Analysis Methodology Limitations")
        for lim in limitations:
            story.append(Paragraph(f"• {lim}", Styles.body))
    story.append(Spacer(1, 3 * mm))
    story.append(_ev_tag(section.get("evidence_ids", [])))
    story.append(PageBreak())


def _build_evidence_appendix(story: list, evidence: dict[str, Any]) -> None:
    story += _section_heading("App.", "Evidence / Traceability Appendix")
    story.append(Paragraph(
        "This appendix lists all approved evidence items from the evidence store "
        "(evidence.json). Each evidence ID shown in the report sections maps to an "
        "entry below. No raw patient data is included; all values are pre-approved "
        "aggregates generated by the deterministic analysis pipeline.",
        Styles.body,
    ))
    story.append(Spacer(1, 3 * mm))
    items = evidence.get("evidence_items", [])
    story.append(evidence_appendix_table(items))
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph(
        f"Total evidence items: {len(items)}",
        Styles.footnote,
    ))


# ── Main generator ────────────────────────────────────────────────────────────

def generate_pdf(
    report_path: str | Path = "output/pader_report.json",
    analysis_path: str | Path = "data/analysis_results.json",
    evidence_path: str | Path = "data/evidence.json",
    output_path: str | Path = "output/Bisoprolol_PADER_Report.pdf",
) -> Path:
    """Generate the PADER PDF and return the output path."""
    report_path   = Path(report_path)
    analysis_path = Path(analysis_path)
    evidence_path = Path(evidence_path)
    output_path   = Path(output_path)

    report   = json.loads(report_path.read_text(encoding="utf-8"))
    analysis = json.loads(analysis_path.read_text(encoding="utf-8"))
    evidence = json.loads(evidence_path.read_text(encoding="utf-8"))

    output_path.parent.mkdir(parents=True, exist_ok=True)

    period_start = analysis["reporting_period"]["start_date"]["value"]
    period_end   = analysis["reporting_period"]["end_date"]["value"]
    report_period = f"{period_start} – {period_end}"

    # ── Doc template ────────────────────────────────────────────────
    on_page = _make_header_footer("Bisoprolol", report_period)

    # Cover frame — full bleed (no margins)
    cover_frame = Frame(0, 0, PAGE_W, PAGE_H, leftPadding=0, rightPadding=0,
                        topPadding=0, bottomPadding=0, id="cover")
    # Content frame — with margins
    content_frame = Frame(
        MARGIN_LEFT, MARGIN_BOTTOM,
        CONTENT_W, PAGE_H - MARGIN_TOP - MARGIN_BOTTOM,
        leftPadding=0, rightPadding=0, topPadding=0, bottomPadding=0,
        id="content",
    )

    doc = BaseDocTemplate(
        str(output_path),
        pagesize=A4,
        leftMargin=0, rightMargin=0,
        topMargin=0, bottomMargin=0,
    )
    cover_template  = PageTemplate(id="Cover",   frames=[cover_frame],
                                   onPage=on_page)
    content_template = PageTemplate(id="Content", frames=[content_frame],
                                    onPage=on_page)
    doc.addPageTemplates([cover_template, content_template])

    # ── Story ────────────────────────────────────────────────────────
    story: list = []

    # 0. Cover
    _build_cover(story, report, analysis)
    story.append(NextPageTemplate("Content"))

    # 1. TOC
    section_names = [
        "Reporting Period",
        "Narrative Summary and Analysis",
        "Summary Analysis of Cases",
        "Reaction / Adverse Event Analysis",
        "Serious Cases / 15-Day Alerts",
        "Trends and Important Observations",
        "History of Actions",
        "Case Index / Listing",
        "Data Limitations",
    ]
    _build_toc(story, section_names)

    # 2. Sections
    _build_reporting_period(story, report, analysis)
    _build_narrative(story, report, analysis)
    _build_case_summary(story, report, analysis)
    _build_reaction_analysis(story, report, analysis)
    _build_serious_alerts(story, report, analysis)
    _build_trends(story, report, analysis)
    _build_history_of_actions(story, report)
    _build_case_index(story, report)
    _build_data_limitations(story, report, analysis)

    # 3. Evidence appendix
    _build_evidence_appendix(story, evidence)

    doc.build(story)
    return output_path


# ── CLI ───────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a professional PADER-style PDF report."
    )
    parser.add_argument("--report",   default="output/pader_report.json")
    parser.add_argument("--analysis", default="data/analysis_results.json")
    parser.add_argument("--evidence", default="data/evidence.json")
    parser.add_argument("--output",   default="output/Bisoprolol_PADER_Report.pdf")
    args = parser.parse_args()

    print(f"Generating PDF from {args.report} …")
    path = generate_pdf(
        report_path=args.report,
        analysis_path=args.analysis,
        evidence_path=args.evidence,
        output_path=args.output,
    )
    print(f"OK  PDF written to {path}")


if __name__ == "__main__":
    main()
